### ISSUE TITLE
Configs of Adam for training ViT

### ISSUE THREAD

**Issue by zhengmeixi** [Ardcy/Lookaround#2]
Hi, thanks for your job and for sharing the code.

I'm trying to reproduce the result in table3 about finetuning ViT on cifar10 with SWA(98.47% reported). The  paper appendix C.2 said the adam weight decay should be set as 0.01: "For the training of ViT-B/16, we used the Adam optimizer, starting with a learning rate of 0.00001. We set β1 to 0.9, β2 to 0.999, and applied a weight decay of 0.01." However, in code train_vit_cifar10_pretrain.yaml, the adam weight decay is set as 0.00005. Which value should I use?

**Comment by zhengmeixi** [comment]
To reproduce ViT-B/16 SWA CIFAR-10 in table 3(98.47%), I use the following yaml file
```
MODEL:
  NAME: 'vit'
  CLASSES: 10
  DEVICE: 'cuda'
  PRETRAINED: True

DATA_DIR: 'dataset'

DATASET:
  IMAGESIZE: 224
  NAME: 'cifar10'

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  Adam_LR: 0.001
  Adam_Beta1: 0.9
  Adam_Beta2: 0.999
  Adam_weight_decay: 0.00005
  LR: 0.1
  BATCH_SIZE: 64
  SCHEDULER: 'Cosine'
  SWA_LR: 0.0008
```
with script
`--yaml_path train_vit_cifar10_pretrain.yaml --train_mode TRAIN_SWA --cuda_id 0 --data_dir /data/cifar10 --out ./out/ --optimizer Adam`

To reproduce ViT-B/16 Lookaround CIFAR-10 in table 3(98.71%), I use the following yaml file
```
MODEL:
  NAME: 'vit'
  CLASSES: 10
  DEVICE: 'cuda'
  PRETRAINED: True

DATA_DIR: 'dataset'

DATASET:
  IMAGESIZE: 224
  NAME: 'cifar10'

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  Adam_LR: 0.001
  Adam_Beta1: 0.9
  Adam_Beta2: 0.999
  Adam_weight_decay: 0.00005  # these adam optimizer config seems wouldn't work and will be covered by Lookaround optimizer
  LR: 0.1
  BATCH_SIZE: 64
  SCHEDULER: 'Cosine'
```
with script
--yaml_path train_vit_cifar10_pretrain.yaml --train_mode TRAIN_LOOKAROUND --cuda_id 0 --data_dir /data/cifar10 --out ./out/ --optimizer Lookaround

Can you help me check whether I use the correct configs? Thanks
